add v100-docs
UofT-EcoSystem/hfta pull request #27
Opened 2021-04-19 12:02 UTC by ypm1999

* [ x ] Tested
* [ x ] Formatted with YAPF

2021-04-24 05:59 UTC, wangshangsam requested changes

2021-04-24 05:59 UTC, wangshangsam commented on docs/mlsys21/v100_throughputs.md
> +- The host resource contains 8 vCPUs, 61 GB memory, but docker instances will limit this.
```
The p3.2xlarge instance contains 8 vCPUs and 61 GB host memory. 
If you selected a larger instance with more GPUs, docker can limit the amount 
of host resource allocated per GPU.
```

2021-04-24 05:59 UTC, wangshangsam commented on docs/mlsys21/v100_throughputs.md
> +- Nsight Compute: version `3.1.72`, downloaded under `third_party/nsys/nsys_cli_2020.3.1.72.deb`
This is actually Nsight System, not Nsight Compute.

2021-04-24 05:59 UTC, wangshangsam commented on docs/mlsys21/v100_throughputs.md
> +- NVIDIA Nsight Computer at: <https://developer.nvidia.com/nsight-compute>
Should be Nsight System.

2021-04-24 05:59 UTC, wangshangsam commented on docs/mlsys21/v100_throughputs.md
> +# build the image, select from native1.6-cu10.2, nvidia20.06, nvidia20.08
V100 and RTX6000 should only select `native1.6-cu10.2`

2021-04-24 05:59 UTC, wangshangsam commented on docs/mlsys21/v100_throughputs.md
> +```
```
#### Reuse prebuilt docker image
If you do not wish to build the docker image from scratch, you can reuse the
prebuilt docker image that we provide:
` ` ` 
docker pull wangshangsam/hfta:mlsys21_native1.6-cu10.2
docker tag wangshangsam/hfta:mlsys21_native1.6-cu10.2 hfta:dev
` ` ` 
```

2021-04-24 05:59 UTC, wangshangsam commented on docs/mlsys21/v100_throughputs.md
> +# you will need to provide a placeholder mount point for data directory
`for data directory` -> `for the data directory`

2021-04-24 05:59 UTC, wangshangsam commented on docs/mlsys21/v100_throughputs.md
> +source benchmarks/workflow.sh cuda a100 <optional: output root dir of the benchmark output>
This is a tutorial for V100 or RTX6000, so the example `source` command should be 
```
source benchmarks/workflow.sh cuda v100
source benchmarks/workflow.sh cuda rtx6000
```

2021-04-24 05:59 UTC, wangshangsam commented on docs/mlsys21/v100_throughputs.md
> +Finally, you should be able to see the `.csv` and `.png` files under the output directory (`./benchmarks (or the directory you specified above)`).
What about the partially fused resnet experiment?

2021-04-28 04:50 UTC, nixli commented on docs/mlsys21/v100_throughputs.md
> +
Driver Version: 450.66 , driver CUDA version 11.0
Description:	Ubuntu 18.04.5 LTS
Docker version 20.10.2, build 2291f61
nvidia-container-runtime version  runc version 1.0.0-rc92, commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff, spec: 1.0.2-dev
GPU: Quadro RTX 6000 24GB

2021-05-01 21:05 UTC, wangshangsam requested changes

2021-05-01 21:05 UTC, wangshangsam commented on docs/mlsys21/v100_rtx6000_throughputs.md.md
> +=============
The output below is actually not what you would see from an `native1.6-cu10.2` image (notice the `Various files include modifications (c) NVIDIA CORPORATION. All rights reserved.` here, which means NVIDIA-built NGC images). 

Just remove the output.

2021-05-01 21:19 UTC, wangshangsam commented on docs/mlsys21/v100_throughputs.md
> +
Hmmm... what exactly is `runc version 1.0.0-rc92, commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff, spec: 1.0.2-dev`? As in is it `1.0.0-rc92` or `1.0.2-dev`? I don't quite understand this part.

2021-05-02 03:11 UTC, nixli commented on docs/mlsys21/v100_throughputs.md
> +
sorry for the confusion, the correct version should be:
2.5.0-1
As shown by 
```bash
dpkg -l | grep nvidia-docker2
```

2021-05-05 16:29 UTC, wangshangsam approved these changes
LGTM!

2021-05-08 13:44 UTC, merged